### ISSUE TITLE
Coding Style Guidelines

### ISSUE THREAD

**Issue by psturmfels** [psturmfels/ios-team#13]
This project is in desperate need of written documentation about style guidelines.

**Comment by dickrp** [comment]
Can you be more specific? UI? Coding? What? I may be able to help.

**Comment by psturmfels** [comment]
Now that you mention it, a style guideline for both is a good idea. This post was meant to convey the need specifically for a coding style guideline. I'll change the title to reflect that.

**Comment by psturmfels** [comment]
Fixed with 493c437d3722a878eb3c0cbc1e0c568f5612691e
