### ISSUE TITLE
Persistent Storage

### ISSUE THREAD

**Issue by psturmfels** [psturmfels/ios-team#15]
I need a dedicated iOS developer to fully understand how Core Data works. 

That individual then needs to review how it is used in this app, and perform tests to validate that it
works correctly in all environments. 

If flaws are found with the current storage methods, or if improvements need to be made, 
then they should be merged in with the current master as soon as possible.

**Comment by psturmfels** [comment]
First steps: lookup and understand "NSFetchedResultsController", https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/CoreData/index.html
"NSManagedObjectContext", "Core Data Entities"

Once you are done with that: Understand the concept of "coreData Migration" and implement them into our app pls

**Comment by qinyeli** [comment]
"Trasient attributes are properties that you define as part of the model, but which are not saved to the persistent store as part of an entity instance's data"

Thought that may be suitable for AnonymouseMessage.

**Comment by qinyeli** [comment]
How to cause migration error? Even if I create and use datamodel version2 it seems to be working perfectly.

**Comment by psturmfels** [comment]
User Defaults handling was improved with 43ef180e1bb44208fd54b29c4f8bc537dc187ce6

**Comment by qinyeli** [comment]
Message is consistent over recompilation, but not termination right now..

**Comment by psturmfels** [comment]
I don't understand what this issue ^ is above. Can you be more descriptive? I cannot replicate any failures with persistent storage on my phone, using the most recent version of master.

**Comment by qinyeli** [comment]
From the commit yesterday, those data stored in disk would appear after recompilation.
However, the messages disappear after termination. (And the weird thing is that they sometimes show up after termination.)

**Comment by psturmfels** [comment]
What does this mean? Are you saying that, when you close the app and re-open it, the messages are gone? I cannot replicate this issue.

**Comment by qinyeli** [comment]
Yes that is what I mean. The message are gone if I close it and re-open. But they will appear after I recompile.

**Comment by qinyeli** [comment]
## Encryption of Core Data

The Core Data itself does provide encryption and decryption, but it only ensures that the data are safe when the device is not unlocked ([ref])(http://stackoverflow.com/questions/23201917/ios-core-data-encryption). The data is stored in the `.sqlite` file directly, so to encrypt message on Core Data
1. We can either encrypt every single message
   - The data structure would still be visible
   - Poor performance
2. or encrypt the `.sqlite` file.
   - Need customization of Core Data
   - The only available solution is [/project-imas/encrypted-core-data](https://github.com/project-imas/encrypted-core-data)
     - It use [SQLCipher](https://github.com/sqlcipher/sqlcipher)

**Comment by psturmfels** [comment]
Aha this is an interesting dichotomy. We can discuss this after our meeting today – it might not be necessary to do any extra encryption.
