### ISSUE TITLE
Cannot send messages to each other

### ISSUE THREAD

**Issue by yufansun** [psturmfels/ios-team#19]
Tested on phone, but we cannot send messages to each other.

**Comment by psturmfels** [comment]
I believe the broadcast/advertise buttons were taken out with 9988c799982e3768eb52f65bf575984fc3764330. We need to replace the buttons with background threads.

**Comment by psturmfels** [comment]
Should be fixed with 5b17a9b62b2edcd725f7b73d4dc9039cd61e3d5a
