### ISSUE TITLE
Adoption of Model-View-Controller Design Pattern

### ISSUE THREAD

**Issue by qinyeli** [psturmfels/ios-team#22]
Since the project is getting larger and larger, we need a method to neatly modularize the project.
The project is currently roughly divided into files according to UIView(Controller)s and functions, which was fine, but as more UI definitions are added, it might be a better choice to split View and ViewControllers

Official Documentation: https://developer.apple.com/library/content/documentation/General/Conceptual/DevPedia-CocoaCore/MVC.html
Other:
https://www.raywenderlich.com/86477/introducing-ios-design-patterns-in-swift-part-1

**Comment by psturmfels** [comment]
Was this not addressed by 1fc50a85908fe851189830e6cd2cd0aaf4354b61 and 52dc490b5c221fa9c805127afd9606597aab7e87?

**Comment by qinyeli** [comment]
Yes the models are separated now (DataController.swift, ConnectivityController.swift).
But there are a bunch of UI settings in TableViewController.swift. If we would have more tableViews in the future, would it be a better approach to have a custom tableView class to do UI settings?

Although, this does not seem to be common. I am searching about this, but it seems that most apps have a custom tableViewCell, but not custom tableView

**Comment by psturmfels** [comment]
Can you be more specific? What settings are you talking about? 

If you are proposing to create a subclass of UITableView, can you justify doing this over creating an abstract sub-class of UITableViewController and having all of our UITableViewControlllers inherit from the base?

There is nothing _wrong_ with subclassing UITableView, but it is relatively uncommon and seems to be unecessary, since all of the necessary tableView behavior is already built into UITableView.

**Comment by qinyeli** [comment]
```
//Set up the tableView style
        self.tableView.separatorStyle = UITableViewCellSeparatorStyle.singleLine
        self.tableView.separatorColor = UIColor.black
        self.tableView.separatorInset = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)
        self.tableView.cellLayoutMarginsFollowReadableWidth = false
```

Maybe these style settings can be put in a separate place if they would be reused later.
I will try creating a tableView subclass and see if that works.

**Comment by psturmfels** [comment]
I don't think this amount of configuration justifies a separate subclass – it seems pointless, given that we have one tableView. 

If we want more tableViews, we should be using inheritance of viewControllers, not tableView subclassing.
