### ISSUE TITLE
Make detail view be a static table view

### ISSUE THREAD

**Issue by psturmfels** [psturmfels/ios-team#31]
The detail view is currently a non-interactable ui view. It should be changed to a static table view to acommodate tableview cells.

**Comment by psturmfels** [comment]
Hey Yufan – Do you think you could give this a shot? What this entails is the following:
currently the AnonymouseDetailViewController class is just a plain old UIViewController. This means
that it doesn't have the nice auto-scroll capabilities that tableViews have, so if a message is very long we can't scroll to see the end of it. 

To fix this problem, we need to make this class a subclass of UITableViewController and have it only display a single cell, the cell that was tapped. Take a look at how the AnonymouseSettingsViewController is set up to see an example of a static table View.

You can assume that every time the view is about to appear, "createNewCell" will be called, 
and so you should handle the capturing of which cell to display there, by storing the passed-in message as a class parameter and then assigning that to be the only cell in the table view.

Please post comments if this is not clear.

**Comment by qinyeli** [comment]
Yufan, I happend to find something when searching for a solution for my task that might be useful to you. Check [UIScrollView](https://developer.apple.com/reference/uikit/uiscrollview) if you want.

**Comment by psturmfels** [comment]
Closed with f8ec73ff673858947225ba4fbec9208765349957.
