### ISSUE TITLE
Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1

### ISSUE THREAD

**Issue by qinyeli** [psturmfels/ios-team#34]
After updating xcode to version Version 8.1 (8B62), the compiler complains at the `import CryptoSwift` that "Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1".

I tried recompiling CryptoSwift and updating submodule, but neither of them worked.

**Comment by psturmfels** [comment]
Can you try running "git submodule update --remote" and see if the problem persists?

**Comment by psturmfels** [comment]
Also try pulling again – I had to fiddle with git stuff.

**Comment by qinyeli** [comment]
This solved the problem. I did not update with the flag --remote. Thank you.
