### ISSUE TITLE
Displaying error -- post content goes out of screen

### ISSUE THREAD

**Issue by qinyeli** [psturmfels/ios-team#36]
The  content of the post goes out of the screen from the right side.
![](https://cloud.githubusercontent.com/assets/16407701/19815691/0c70c756-9d12-11e6-9007-1acba054c157.jpeg)

**Comment by psturmfels** [comment]
I can't seem to replicate this error. How did you do it?

**Comment by qinyeli** [comment]
I just typed super long post. (Did you try making every word long enough?)
I am sure that everything is up to date (iOS, Xcode, macOS, master branch)

**Comment by psturmfels** [comment]
Nothing seems to replicate this on my phone. I'll take a look this afternoon, but it has something to do with the tableViewCell's getCellHeight methods. Most likely, the cause is that the number "340" is hard-coded in, when this should actually be the width of the screen. Can you experiement with these functions (lines 24 and 34) of AnonymouseTableViewCell and see if you can change those to a non-hard-coded value (e.g. a percentage of the screen's width) to get this to work?

**Comment by qinyeli** [comment]
Unfortunately, I did not bring the lightening charger with me, but I can check it tomorrow.
I would also check if the problem is cause by the card UI, for the text used to start from the left end side of the screen, but now it have to start from the left end of the card, which may caused the text to be unable to fit in the screen.

**Comment by psturmfels** [comment]
Any word on this?

**Comment by qinyeli** [comment]
No.. It is strange though that the behavior is different in iPhone and simulator. While the simulator does not have this error, it has an error in the compose view. 
<img width="372" alt="screen shot 2016-10-29 at 22 42 00" src="https://cloud.githubusercontent.com/assets/16407701/19834129/27c1f922-9e29-11e6-8361-094ddda5547f.png">

**Comment by qinyeli** [comment]
It might be related or unrelated to this problem, but getClippedCellHeight() is called multiple times every time a new message is created.
(Try printing in getClippedCellHeight()!)

Also, I understand the scheme of setting the cellHeight:

```
static func getClippedCellHeight(withMessageText text: String) -> CGFloat {
        let messageLabel: UILabel = UILabel(frame: CGRect(x: 0, y: 0, width: 340.0, height: CGFloat.greatestFiniteMagnitude))
        messageLabel.numberOfLines = 3
        messageLabel.lineBreakMode = NSLineBreakMode.byWordWrapping
        messageLabel.font = messageFont
        messageLabel.text = text
        messageLabel.sizeToFit()
        return messageLabel.frame.size.height + spacing + featuresBarHeight
    }
```

 but are those messageLabel created just to return the cell height? Will they be used somewhere else? If not.. it does not seem to be an efficient practice if there are other methods of doing this.

**Comment by qinyeli** [comment]
I find that the parameter defining the end of the text is currently hard-coded in `createMessageLabel`.

```
    func createMessageLabel(withNumberOfLines numberOfLines: Int) {
        messageLabel = UILabel(frame: CGRect(x: 0, y: 0, width: 340.0, height: CGFloat.greatestFiniteMagnitude))
        messageLabel!.numberOfLines = numberOfLines
        messageLabel!.lineBreakMode = NSLineBreakMode.byTruncatingTail

        messageLabel!.textColor = UIColor.black
        messageLabel!.font = AnonymouseTableViewCell.messageFont
    }
```

Maybe the problem can be fixed by expressing the magic number with some variable

**Comment by yufansun** [comment]
fixed it by changing the hard-coded width to UIScreen.main.bounds.width \* 0.9
