### ISSUE TITLE
Unable to insert message after search (on branch search)

### ISSUE THREAD

**Issue by qinyeli** [psturmfels/ios-team#45]
Message inserted after hitting and dismissing the search bar would not be shown in the table view.
However, if you quit the app and then reopen it, the message would be in the table view.

Cause:
```
func controller(_ controller: NSFetchedResultsController<NSFetchRequestResult>, didChange anObject: Any, at indexPath: IndexPath?, for type: NSFetchedResultsChangeType, newIndexPath: IndexPath?)
```
is not called after hitting and dismissing the search bar. Not sure why this happens though

**Comment by qinyeli** [comment]
In `func filterContentForSearchResult(searchText: String, scope: String = "All") `, set predicate to nil after reloading the table

**Comment by qinyeli** [comment]
Unable to insert text once `try searchResultsController.performFetch()` in `filterContentForSearchResult(searchText: String, scope: String = "All")` is called.

**Comment by qinyeli** [comment]
http://stackoverflow.com/questions/4471289/how-to-filter-nsfetchedresultscontroller-coredata-with-uisearchdisplaycontroll

**Comment by qinyeli** [comment]
Tried calling `fetchedResultsController.performFetch()` in `searchBarCancelButtonClicked()`. Didn't work

**Comment by yufansun** [comment]
This code seems to have both fetchResultsController and searchResultController: https://github.com/damianoct/ConcorsiGazzetta/blob/48790843831f9a95890d227e72be691aff34891c/ConcorsiGazzetta/DDSGazzetteTBC.swift

**Comment by qinyeli** [comment]
Initialized `searchResultsController` independently instead of trying to copy from `fetchedResultsController`.

Namely,
```
    var searchRequest: NSFetchRequest<AnonymouseMessageCore> = NSFetchRequest<AnonymouseMessageCore>(entityName: "AnonymouseMessageCore")
    
    init(withFetchRequest fetchRequest: NSFetchRequest<AnonymouseMessageCore>) {
        self.fetchRequest = fetchRequest
        self.searchRequest.sortDescriptors = fetchRequest.sortDescriptors
        super.init(style: UITableViewStyle.plain)
    }
```

instead of 
```
    init(withFetchRequest fetchRequest: NSFetchRequest<AnonymouseMessageCore>) {
        self.fetchRequest = fetchRequest
        self.searchRequest = fetchRequest
        super.init(style: UITableViewStyle.plain)
    }
```
