### ISSUE TITLE
The messages needs to scroll up when there are a lot of messages

### ISSUE THREAD

**Issue by yufansun** [psturmfels/ios-team#6]
When there are a lot of messages on the screen, for example, more than 20 messages, the messages don't scroll up so that we cannot see the new messages. So we need to find a way to let the messages scroll up and down in the container.

**Comment by psturmfels** [comment]
This feature should be built in to the table view. Try pulling from master; Is this issue fixed?

**Comment by yufansun** [comment]
Yes, it has been fixed now!
